core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
]

operations/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import TreatmentListView
from . import views

app_name = 'operations'

urlpatterns = [
    url(r'^treatment$', views.treatment_create, name='treatment_create'),
    url(r'^treatment/(?P<pk>\d+)/update/$', views.treatment_update, name='treatment_update'),
    url(r'^treatment/(?P<pk>\d+)/delete/$', views.treatment_delete, name='treatment_delete'),
    url(r'^treatments$', TreatmentListView.as_view(), name='treatments'),
]

operations/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

from core.models import TimeStampedModel
from reception.models import Patient
from hospital.models import Diagnose
from staff.models import Doctor, Nurse


# Create your models here.
class Diagnose(TimeStampedModel):
    name = models.CharField(max_length=200)
    code = models.IntegerField(default=0, unique=True)
    description = models.TextField()

    def __str__(self):
        return '{}-{}'.format(self.code, self.name)


class Treatment(TimeStampedModel):
    date = models.DateField(default=timezone.now().date())
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=None)
    symptoms = models.TextField()
    diagnosis = models.ForeignKey(Diagnose, on_delete=None)
    doctors_comments = models.TextField()

    def __str__(self):
        return '{}-{}'.format(self.patient, self.diagnosis)


class Vaccine(TimeStampedModel):
    name = models.CharField(max_length=100)
    live = models.NullBooleanField()
    absorved = models.NullBooleanField()
    inactivated = models.NullBooleanField()
    oral = models.NullBooleanField()

    def __str__(self):
        return self.name

class VaccineApplied(TimeStampedModel):
    date = models.DateField(default=timezone.now().date())
    vaccine = models.ForeignKey(Vaccine)
    patient = models.ForeignKey(Patient)
    nurse = models.ForeignKey(Nurse)

    def __str__(self):
        return '%s | by  %s (%s)' % (self.patient, self.nurse, self.date)

    class Meta:
        verbose_name = 'Vaccine Applied'
        verbose_name_plural = 'Vaccines usage'


class Test(TimeStampedModel):
    mame = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class MedicalTest(TimeStampedModel):
    date = models.DateField(default=timezone.now().date())
    patient = models.ForeignKey(Patient)
    test = models.ForeignKey(Test)
    results = models.CharField(max_length=500)
    status = models.BooleanField()

    def __str__(self):
        return '{}-{}'.format(self.patient, self.test.name)

operations/forms.py
from django import forms
from operations.models import Treatment

# crispy_forms imports
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, MultiWidgetField, Submit

class TreatmentForm(forms.ModelForm):
    # TODO: Define other fields here

    class Meta:
        model = Treatment
        fields = ['patient', 'doctor', 'date', 'symptoms', 'diagnosis', 'doctors_comments']

        labels = {
            'doctors_comments': "Doctor's Comments"
            }

        widgets = {
            'date': forms.SelectDateWidget(years=[str(val) for val in range(1998, 2017)]),
            'symptoms': forms.Textarea(attrs={'rows':4, 'style':'resize:none;'}),
            'doctors_comments': forms.Textarea(attrs={'rows':4, 'style':'resize:none;'}),
            }

    def __init__(self, *args, **kwargs):
        super(TreatmentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        # self.fields['symptoms'].widget.attrs['style'] = 'resize:none' //setting textarea resize to none
        # self.helper.form_class = 'form-horizontal'
        # self.helper.form_method = 'post'
        # self.helper.add_input(Submit('submit', 'Save'))
        self.helper.form_tag = False

        self.helper.layout = Layout(
            'patient',
            'doctor',
            MultiWidgetField(
                'date',
                attrs=(
                    {'style': 'width: 32.8%; display: inline-block;'}
                )
            ),
            'symptoms',
            'diagnosis',
            'doctors_comments',
        )


    def clean(self):
        cleaned_data = super(TreatmentForm, self).clean()
        return cleaned_data

operations/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.contrib.messages.views import SuccessMessageMixin

from django.http import JsonResponse
from django.template.loader import render_to_string
from django.shortcuts import render, get_object_or_404

from django.views.generic import CreateView, ListView
from .forms import TreatmentForm
from .models import Treatment

# create fbv for a treatment modal form for create, update and delete
def save_treatment_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            treatments = Treatment.objects.all()
            data['html_treatment_list'] = render_to_string("operations/includes/partial_treatment_list.html",
                {'treatments': treatments}
            )
        else:
            data['form_is_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

def treatment_create(request):
    if request.method == 'POST':
        form = TreatmentForm(request.POST)
    else:
        form = TreatmentForm()
    return save_treatment_form(request, form, 'operations/treatment_form.html')


def treatment_update(request, pk):
    treatment = get_object_or_404(Treatment, pk=pk)
    if request.method == 'POST':
        form = TreatmentForm(request.POST, instance=treatment)
    else:
        form = TreatmentForm(instance=treatment)
    return save_treatment_form(request, form, 'operations/treatment_update.html')


def treatment_delete(request, pk):
    treatment = get_object_or_404(Treatment, pk=pk)
    data = dict()
    if request.method == 'POST':
        treatment.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        treatments = Treatment.objects.all()
        data['html_treatment_list'] = render_to_string('operations/includes/partial_treatment_list.html',
            {'treatments': treatments}
        )
    else:
        context = {'treatment': treatment}
        data['html_form'] = render_to_string('operations/treatment_delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)


class TreatmentListView(ListView):
    context_object_name = 'treatments'
    model = Treatment
    template_name = 'operations/treatment_list.html'

    def get_queryset(self):
        return Treatment.objects.all()

operations/templates/operations/treatment_delete.html
<form method="post" action="{% url 'operations:treatment_delete' treatment.id %}" class="js-treatment-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm treatment deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete treatment <strong>{{ treatment.patient }} {{ treatment.diagnosis }}</strong>? </p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete Treatment</button>
  </div>
</form>

operations/templates/operations/treatment_form.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'operations:treatment_create' %}" class="js-treatment-create-form form-horizontal">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a Treatment</h4>
  </div>

  <div class="modal-body">
      {% crispy form %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create Treatment</button>
  </div>

</form>

operations/templates/operations/treatment_list.html
{% extends 'hospital/base.html' %}

{% load staticfiles %}

{% block title %}Treatments{{ block.super }}{% endblock title %}

{% block javascript %}
  <script src="{% static 'operations/js/modal.js' %}"></script>
  <script src="{% static 'operations/css/style.css' %}"></script>
{% endblock javascript %}


{% block content %}
  <div class="container">
    <h1 class="page-header">Treatments</h1>

    <!-- BUTTON TO TRIGGER THE ACTION -->
    <p>
      <button type="button"
              class="btn btn-primary js-create-treatment"
              data-url="{% url 'operations:treatment_create' %}">
        <span class="glyphicon glyphicon-plus"></span>
        New treatment
      </button>
    </p>

    <table class="table" id="treatment-table">
      <thead>
        <tr>
          <th>#</th>
          <th>Patient</th>
          <th>Doctor</th>
          <th>Date</th>
          <th>Symptoms</th>
          <th>Diagnosis</th>
          <th>Doctor's Comments</th>
        </tr>
      </thead>
      <tbody>
        {% include 'operations/includes/partial_treatment_list.html' %}
      </tbody>
    </table>

    <!-- THE MODAL WE WILL BE USING -->
    <div class="modal fade" id="modal-treatment">
      <div class="modal-dialog">
        <div class="modal-content">
        </div>
      </div>
    </div>

  </div>

{% endblock %}

operations/templates/operations/treatment_update.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'operations:treatment_update' pk=form.instance.pk %}" class="js-treatment-update-form form-horizontal">
  {% csrf_token %}
  <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update Treatment</h4>
  </div>

  <div class="modal-body">
      {% crispy form %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update Treatment</button>
  </div>

</form>