core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
]

staff/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import DoctorListView
from . import views

app_name = 'staff'

urlpatterns = [
    url(r'^doctor$', views.doctor_create, name='doctor_create'),
    url(r'^doctor/(?P<pk>\d+)/update/$', views.doctor_update, name='doctor_update'),
    url(r'^doctor/(?P<pk>\d+)/delete/$', views.doctor_delete, name='doctor_delete'),
    url(r'^doctors$', DoctorListView.as_view(), name='doctors'),
]

staff/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

from core.models import TimeStampedModel
from hospital.models import Person


# Create your models here.
class UserType(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'User Type'
        verbose_name_plural = 'User Types'


# def get_doctors():
#     doctor =  UserType.objects.get_or_create(name='Doctors', description='Doctors')
#     return doctor.id
#
# def get_nurses():
#     nurse = UserType.objects.get_or_create(name='Nurses', description='Nurses')
#     return nurse.id


class Speciality(TimeStampedModel):
    specialty = models.CharField(max_length=100)

    def __str__(self):
        return self.specialty

    class Meta:
        verbose_name = 'Specialty'
        verbose_name_plural = 'Specialties'


class Doctor(Person):
    person = models.OneToOneField(User, related_name='doctors')
    avatar = models.ImageField(upload_to='avatars/doctors', null=True, blank=True)
    specialty = models.ManyToManyField(Speciality)
    user_type = models.ForeignKey(UserType, related_name='doctors')

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class Nurse(Person):
    person = models.OneToOneField(User, related_name='nurses')
    avatar = models.ImageField(upload_to='avatars/nurses', null=True, blank=True)
    specialty = models.ManyToManyField(Speciality)
    user_type = models.ForeignKey(UserType, related_name='nurses')

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class OtherStaff(Person):
    person = models.OneToOneField(User)
    avatar = models.ImageField(upload_to='avatars/otherstaff', null=True, blank=True)
    specialty = models.ManyToManyField(Speciality)
    user_type = models.ForeignKey(UserType)

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

staff/forms.py
from django import forms
from staff.models import Doctor

# crispy_forms imports
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, MultiWidgetField, Submit

class DoctorForm(forms.ModelForm):
    # TODO: Define other fields here

    class Meta:
        model = Doctor
        fields = ['first_name', 'last_name', 'gender', 'dob', 'age', 'country', 'city', 'address']

        labels = {
            'dob': 'Date of Birth'
        }
        widgets = {
            'dob': forms.SelectDateWidget(years=[str(val) for val in range(1998, 2017)]),
        }

    def __init__(self, *args, **kwargs):
        super(DoctorForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        # self.helper.form_class = 'form-horizontal'
        # self.helper.form_method = 'post'
        # self.helper.add_input(Submit('submit', 'Save'))
        self.helper.form_tag = False

        self.helper.layout = Layout(
            'first_name',
            'last_name',
            'gender',
            MultiWidgetField(
                'dob',
                attrs=(
                    {'style': 'width: 32.8%; display: inline-block;'}
                )
            ),
            'age',
            'country',
            'city',
            'address',
        )

    def clean(self):
        cleaned_data = super(DoctorForm, self).clean()
        return cleaned_data

staff/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import CreateView, ListView
from django.contrib.messages.views import SuccessMessageMixin

from django.http import JsonResponse
from django.template.loader import render_to_string
from django.shortcuts import render, get_object_or_404

from .models import Doctor
from .forms import DoctorForm

# create fbv for a doctor modal form for create, update and delete
def save_doctor_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            doctors = Doctor.objects.all()
            data['html_doctor_list'] = render_to_string("staff/includes/partial_doctor_list.html",
                {'doctors': doctors}
            )
        else:
            data['form_is_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

def doctor_create(request):
    if request.method == 'POST':
        form = DoctorForm(request.POST)
    else:
        form = DoctorForm()
    return save_doctor_form(request, form, 'staff/doctor_form.html')


def doctor_update(request, pk):
    doctor = get_object_or_404(Doctor, pk=pk)
    if request.method == 'POST':
        form = DoctorForm(request.POST, instance=doctor)
    else:
        form = DoctorForm(instance=doctor)
    return save_doctor_form(request, form, 'staff/doctor_update.html')


def doctor_delete(request, pk):
    doctor = get_object_or_404(Doctor, pk=pk)
    data = dict()
    if request.method == 'POST':
        doctor.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        doctors = Doctor.objects.all()
        data['html_doctor_list'] = render_to_string('staff/includes/partial_doctor_list.html',
            {'doctors': doctors}
        )
    else:
        context = {'doctor': doctor}
        data['html_form'] = render_to_string('staff/doctor_delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)


class DoctorListView(ListView):
    context_object_name = 'doctors'
    model = Doctor
    template_name = 'staff/doctor_list.html'

    def get_queryset(self):
        return Doctor.objects.all()

staff/templates/staff/doctor_delete.html
<form method="post" action="{% url 'staff:doctor_delete' doctor.id %}" class="js-doctor-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm doctor deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete doctor <strong>{{ doctor.first_name }} {{ doctor.last_name }}</strong>? </p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete Doctor</button>
  </div>
</form>

staff/templates/staff/doctor_form.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'staff:doctor_create' %}" class="js-doctor-create-form form-horizontal">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a Doctor</h4>
  </div>

  <div class="modal-body">
      {% crispy form %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create Doctor</button>
  </div>

</form>

staff/templates/staff/doctor_list.html
{% extends 'hospital/base.html' %}

{% load staticfiles %}

{% block title %}Doctors{{ block.super }}{% endblock title %}

{% block javascript %}
  <script src="{% static 'staff/js/modal.js' %}"></script>
  <script src="{% static 'staff/css/style.css' %}"></script>
{% endblock javascript %}


{% block content %}
  <div class="container">
    <h1 class="page-header">Doctors</h1>

    <!-- BUTTON TO TRIGGER THE ACTION -->
    <p>
      <button type="button"
              class="btn btn-primary js-create-doctor"
              data-url="{% url 'staff:doctor_create' %}">
        <span class="glyphicon glyphicon-plus"></span>
        New doctor
      </button>
    </p>

    <table class="table" id="doctor-table">
      <thead>
        <tr>
          <th>#</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Gender</th>
          <th>Date of Birth</th>
          <th>Age</th>
          <th>Country</th>
          <th>City</th>
          <th>Address</th>
        </tr>
      </thead>
      <tbody>
        {% include 'staff/includes/partial_doctor_list.html' %}
      </tbody>
    </table>

    <!-- THE MODAL WE WILL BE USING -->
    <div class="modal fade" id="modal-doctor">
      <div class="modal-dialog">
        <div class="modal-content">
        </div>
      </div>
    </div>

  </div>

{% endblock %}

staff/templates/staff/doctor_update.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'staff:doctor_update' pk=form.instance.pk %}" class="js-doctor-update-form form-horizontal">
  {% csrf_token %}
  <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update Doctor</h4>
  </div>

  <div class="modal-body">
      {% crispy form %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update Doctor</button>
  </div>

</form>