accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm

app_name = 'accounts'

urlpatterns = [
    url(r'^login$', auth_views.login, {
            'template_name': 'accounts/login.html',
            'authentication_form': AuthenticationForm
        },
        name='login'
    ),
    url(r'^logout/$', auth_views.logout_then_login, {'login_url':'accounts:login'}, name='logout'),
]

core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
]

finance/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import BillingListView
from . import views

app_name = 'finance'

urlpatterns = [
    url(r'^billing$', views.billing_create, name='billing_create'),
    url(r'^billing/(?P<pk>\d+)/update/$', views.billing_update, name='billing_update'),
    url(r'^billing/(?P<pk>\d+)/delete/$', views.billing_delete, name='billing_delete'),
    url(r'^billings$', BillingListView.as_view(), name='billings'),
]

hospital/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from .views import IndexView, RoomListView, DiagnoseListView
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm

app_name = 'hospital'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^room$', views.room_create, name='room_create'),
    url(r'^room/(?P<pk>\d+)/update/$', views.room_update, name='room_update'),
    url(r'^room/(?P<pk>\d+)/delete/$', views.room_delete, name='room_delete'),
    url(r'^rooms$', RoomListView.as_view(), name='rooms'),
    url(r'^diagnose$', views.diagnose_create, name='diagnose_create'),
    url(r'^diagnose/(?P<pk>\d+)/update/$', views.diagnose_update, name='diagnose_update'),
    url(r'^diagnose/(?P<pk>\d+)/delete/$', views.diagnose_delete, name='diagnose_delete'),
    url(r'^diagnoses$', DiagnoseListView.as_view(), name='diagnoses'),
]

reception/urls.py
from django.conf.urls import url
from django.contrib import admin
from reception.views import PatientCreateView, In_patientCreateView, Out_patientCreateView, PatientListView, In_patientListView

app_name = 'reception'

urlpatterns = [
    url(r'^patient$', PatientCreateView.as_view(), name='patient'),
    url(r'^patients$', PatientListView.as_view(), name='patients'),
    url(r'^in-patient$', In_patientCreateView.as_view(), name='in_patient'),
    url(r'^out-patient$', Out_patientCreateView.as_view(), name='out_patient'),
]

staff/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import DoctorListView
from . import views

app_name = 'staff'

urlpatterns = [
    url(r'^doctor$', views.doctor_create, name='doctor_create'),
    url(r'^doctor/(?P<pk>\d+)/update/$', views.doctor_update, name='doctor_update'),
    url(r'^doctor/(?P<pk>\d+)/delete/$', views.doctor_delete, name='doctor_delete'),
    url(r'^doctors$', DoctorListView.as_view(), name='doctors'),
]

hospital/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from core.models import TimeStampedModel


class Person(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    dob = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    phone = models.CharField(max_length=15, default=0)
    age = models.IntegerField(default=0)
    country = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    next_of_kin = models.CharField(max_length=200)
    next_of_kin_contact_no = models.CharField(max_length=200)

    class Meta:
        abstract = True


class Department(TimeStampedModel):
    name = models.CharField(max_length=100)
    director = models.ForeignKey(User, null=True)
    staff = models.ManyToManyField(User, related_name='+')

    def __str__(self):
        return self.name


class RoomType(TimeStampedModel):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Room type'
        verbose_name_plural = 'Room types'


class Room(TimeStampedModel):
    room_type = models.ForeignKey(RoomType)
    room_number = models.IntegerField(default=0, blank=True)
    departmnt = models.ForeignKey(Department)

    def __str__(self):
        return '{}-{}'.format(self.room_number, self.room_type.name)


class Diagnose(TimeStampedModel):
    name = models.CharField(max_length=200)
    code = models.IntegerField(default=0, unique=True)
    description = models.TextField()

    def __str__(self):
        return '{}-{}'.format(self.code, self.name)


class HospitalStats(TimeStampedModel):
    totalAdmins = models.IntegerField()
    totalDoctors = models.IntegerField()
    totalNurses = models.IntegerField()
    totalPatients = models.IntegerField()
    successfulLogins = models.IntegerField()
    failedLogins = models.IntegerField()
    appointmentsCreated = models.IntegerField()
    medicationsPrescribed = models.IntegerField()
    testsConducted = models.IntegerField()
    messagesSent = models.IntegerField()
    notificationsReceived = models.IntegerField()
    patientsAdmitted = models.IntegerField()
    oldestUser = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Hospital Statistics'
        verbose_name_plural = 'Hospital Statistics'


class supplier(TimeStampedModel):
    pass

hospital/forms.py
from django import forms
from hospital.models import Diagnose, Room

# crispy_forms imports
from crispy_forms.helper import FormHelper
from crispy_forms.layout import  Submit

class RoomForm(forms.ModelForm):
    # TODO: Define other fields here

    class Meta:
        model = Room
        fields = ['room_number', 'room_type']

        labels = {
            'room_number': 'Room Number',
            'room_type': 'Room Type'
        }

    def __init__(self, *args, **kwargs):
        super(RoomForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        # self.helper.form_class = 'form-horizontal'
        # self.helper.form_method = 'post'
        # self.helper.add_input(Submit('submit', 'Save'))
        self.helper.form_tag = False

    def clean(self):
        cleaned_data = super(RoomForm, self).clean()
        return cleaned_data


class DiagnoseForm(forms.ModelForm):
    # TODO: Define other fields here

    class Meta:
        model = Diagnose
        fields = ['name', 'code', 'description']

        widgets = {
            "description": forms.Textarea(
                attrs={'rows':4, 'style':'resize:none;'}
                )
            }

    def __init__(self, *args, **kwargs):
        super(DiagnoseForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        # self.helper.form_class = 'form-horizontal'
        # self.helper.form_method = 'post'
        self.helper.form_tag = False
        # self.helper.add_input(Submit('submit', 'Save'))

    def clean(self):
        cleaned_data = super(DiagnoseForm, self).clean()
        return cleaned_data

hospital/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# django imports
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView, CreateView, ListView
from django.views import View
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from django.http import JsonResponse
from django.template.loader import render_to_string
from django.shortcuts import render, get_object_or_404

# project imports
from .models import Diagnose, Room
from .forms import DiagnoseForm, RoomForm


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'hospital/index.html'


# create fbv for a diagnose modal form for create, update and delete
def save_diagnose_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            diagnoses = Diagnose.objects.all()
            data['html_diagnose_list'] = render_to_string("hospital/includes/partial_diagnose_list.html",
                {'diagnoses': diagnoses}
            )
        else:
            data['form_is_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

def diagnose_create(request):
    if request.method == 'POST':
        form = DiagnoseForm(request.POST)
    else:
        form = DiagnoseForm()
    return save_diagnose_form(request, form, 'hospital/diagnose_form.html')


def diagnose_update(request, pk):
    diagnose = get_object_or_404(Diagnose, pk=pk)
    if request.method == 'POST':
        form = DiagnoseForm(request.POST, instance=diagnose)
    else:
        form = DiagnoseForm(instance=diagnose)
    return save_diagnose_form(request, form, 'hospital/diagnose_update.html')


def diagnose_delete(request, pk):
    diagnose = get_object_or_404(Diagnose, pk=pk)
    data = dict()
    if request.method == 'POST':
        diagnose.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        diagnoses = Diagnose.objects.all()
        data['html_diagnose_list'] = render_to_string('hospital/includes/partial_diagnose_list.html',
            {'diagnoses': diagnoses}
        )
    else:
        context = {'diagnose': diagnose}
        data['html_form'] = render_to_string('hospital/diagnose_delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)

# create fbv for a room modal form for create, update and delete
def save_room_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            rooms = Room.objects.all().order_by('room_number')
            data['html_room_list'] = render_to_string('hospital/includes/partial_room_list.html',
                {'rooms': rooms}
            )
        else:
            data['form_is_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

def room_create(request):
    if request.method == 'POST':
        form = RoomForm(request.POST)
    else:
        form = RoomForm()
    return save_room_form(request, form, 'hospital/room_form.html')


def room_update(request, pk):
    room = get_object_or_404(Room, pk=pk)
    if request.method == 'POST':
        form = RoomForm(request.POST, instance=room)
    else:
        form = RoomForm(instance=room)
    return save_room_form(request, form, 'hospital/room_update.html')


def room_delete(request, pk):
    room = get_object_or_404(Room, pk=pk)
    data = dict()
    if request.method == 'POST':
        room.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        rooms = Room.objects.all().order_by('room_number')
        data['html_room_list'] = render_to_string('hospital/includes/partial_room_list.html',
            {'rooms': rooms}
        )
    else:
        context = {'room': room}
        data['html_form'] = render_to_string('hospital/room_delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)




# cbv listviews for malaika app
class DiagnoseListView(LoginRequiredMixin, ListView):
    context_object_name = 'diagnoses'
    model = Diagnose
    template_name = 'hospital/diagnose_list.html'

    def get_queryset(self):
        return Diagnose.objects.all()


class RoomListView(LoginRequiredMixin, ListView):
    context_object_name = 'rooms'
    model = Room
    template_name = 'hospital/room_list.html'

    def get_queryset(self):
        return Room.objects.all().order_by('room_number')

hospital/templates/hospital/base.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'hospital/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'hospital/css/bootstrap.united.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'hospital/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'hospital/css/fullcalender.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'hospital/css/fullcalender.print.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'hospital/css/datatables.min.css' %}" type="text/css">

    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="{% static 'hospital/css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'reception/css/style.css' %}" type="text/css">
    <title>{% block title %} |Malaika Hospital {% endblock title %}</title>
  </head>

  <body>
    <nav class="navbar-inverse navbar-static-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'hospital:index' %}">Malaika Hospital</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'reception:patients' %}">Reception</a></li>
            <li><a href="{% url 'operations:treatments' %}">Treatment</a></li>
            <li><a href="{% url 'finance:billings' %}">Finance</a></li>
            <li><a href="{% url 'hospital:diagnoses' %}">Diagnoses</a></li>
            <li><a href="{% url 'hospital:rooms' %}">Rooms</a></li>
            <li><a href="{% url 'staff:doctors' %}">Doctors</a></li>
            <li class="nav navbar-nav">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'reception:patient' %}">Patient</a></li>
                <li><a href="{% url 'reception:in_patient' %}">In_patient</a></li>
                <li><a href="{% url 'reception:out_patient' %}">Out-patient</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                  <li class="nav navbar-nav">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                      <i class="glyphicon glyphicon-user" aria-hidden="true"></i><span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    </ul>
                  </li>
                {% else %}
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                {% endif %}
          </ul>
        </div>
      </div>
    </nav>
      <!-- </div>
    </div> -->

    {% block content %}
    {% endblock content %}

    <footer class="text-center footer">
        <p class="text-center">Copyright &copy;2017 hospital Hospital All Rights Reserved<br/>By Lolany Int.</p>
    </footer>

    <!-- All the link to js scripts to come last. -->
    <script src="{% static 'hospital/js/jquery.min.js' %}"></script>
    <script src="{% static 'hospital/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'hospital/js/datatales.min.js' %}"></script>
    <script src="{% static 'hospital/js/fullcalender.min.js' %}"></script>


    {% block javascript %}
    {% endblock %}

  </body>
</html>

hospital/templates/hospital/diagnose_delete.html
<form method="post" action="{% url 'hospital:diagnose_delete' diagnose.id %}" class="js-diagnose-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm diagnose deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the diagnose <strong>{{ diagnose.name }}</strong>? </p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete diagnose</button>
  </div>
</form>

hospital/templates/hospital/diagnose_form.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'hospital:diagnose_create' %}" class="js-diagnose-create-form form-horizontal">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a Diagnose</h4>
  </div>

  <div class="modal-body">
      {% crispy form %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create Diagnose</button>
  </div>

</form>

hospital/templates/hospital/diagnose_list.html
{% extends 'hospital/base.html' %}

{% load staticfiles %}

{% block title %}Diagnoses{{ block.super }}{% endblock title %}

{% block javascript %}
  <script src="{% static 'hospital/js/modal.js' %}"></script>
{% endblock javascript %}


{% block content %}
  <div class="container">
    <h1 class="page-header">Diagnoses</h1>

    <!-- BUTTON TO TRIGGER THE ACTION -->
    <p>
      <button type="button"
              class="btn btn-primary js-create-diagnose"
              data-url="{% url 'hospital:diagnose_create' %}">
        <span class="glyphicon glyphicon-plus"></span>
        New diagnose
      </button>
    </p>

    <table class="table" id="diagnose-table">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Code</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {% include 'hospital/includes/partial_diagnose_list.html' %}
      </tbody>
    </table>

    <!-- THE MODAL WE WILL BE USING -->
    <div class="modal fade" id="modal-diagnose">
      <div class="modal-dialog">
        <div class="modal-content">
        </div>
      </div>
    </div>

  </div>

{% endblock %}

hospital/templates/hospital/diagnose_update.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'hospital:diagnose_update' pk=form.instance.pk %}" class="js-diagnose-update-form form-horizontal">
  {% csrf_token %}
  <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update Diagnose</h4>
  </div>

  <div class="modal-body">
      {% crispy form %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update Diagnose</button>
  </div>

</form>

hospital/templates/hospital/index.html
{% extends 'hospital/base.html' %}

{% load staticfiles %}

{% block title %} Home {{ block.super }}{% endblock title %}

{% block content %}
    <div class="container index">
      <div class="container text-center">
        {% include "hospital/includes/success_message.html" %}
      </div>
      <div class="container jumbotron main-jumbo">
          <div class="text-center">
              <h2 class="hospital_name">{{ hospital_name|upper }}</h2> <br>
              <strong class="hospital_slogan">{{ hospital_slogan }} </strong><br>
              It to create a challenging learning environment that
              encourages high expectations for success through development-appropriate instruction
              that allows for individual differences and learning styles. Our school promotes a safe,
              orderly, caring, and supportive environment. Each student’s self-esteem is fostered by
              positive relationships with students and staff. We strive to have our parents, teachers, and community members actively involved on our students’ learning.
          </div>
      </div>
{% endblock content %}

hospital/templates/hospital/room_delete.html
<form method="post" action="{% url 'hospital:room_delete' room.id %}" class="js-room-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm room deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the room <strong>{{ room.room_number }}</strong>? </p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete room</button>
  </div>
</form>

hospital/templates/hospital/room_form.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'hospital:room_create' %}" class="js-room-create-form form-horizontal">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a room</h4>
  </div>

  <div class="modal-body">
      {% crispy form %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create Room</button>
  </div>

</form>

hospital/templates/hospital/room_list.html
{% extends 'hospital/base.html' %}

{% load staticfiles %}

{% block javascript %}
  <script src="{% static 'hospital/js/modal.js' %}"></script>
{% endblock javascript %}


{% block content %}
  <div class="container">
    <h1 class="page-header">Rooms</h1>

    <!-- BUTTON TO TRIGGER THE ACTION -->
    <p>
      <button type="button"
              class="btn btn-primary js-create-room"
              data-url="{% url 'hospital:room_create' %}">
        <span class="glyphicon glyphicon-plus"></span>
        New room
      </button>
    </p>

    <table class="table" id="room-table">
      <thead>
        <tr>
          <th>#</th>
          <th>Room Number</th>
          <th>Room Type</th>
        </tr>
      </thead>
      <tbody>
        {% include 'hospital/includes/partial_room_list.html' %}
      </tbody>
    </table>

    <!-- THE MODAL WE WILL BE USING -->
    <div class="modal fade" id="modal-room">
      <div class="modal-dialog">
        <div class="modal-content">
        </div>
      </div>
    </div>

  </div>

{% endblock %}

hospital/templates/hospital/room_update.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'hospital:room_update' pk=form.instance.pk %}" class="js-room-update-form form-horizontal">
  {% csrf_token %}
  <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update room</h4>
  </div>

  <div class="modal-body">
    {% crispy form %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update Room</button>
  </div>

</form>