core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
]

finance/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import BillingListView
from . import views

app_name = 'finance'

urlpatterns = [
    url(r'^billing$', views.billing_create, name='billing_create'),
    url(r'^billing/(?P<pk>\d+)/update/$', views.billing_update, name='billing_update'),
    url(r'^billing/(?P<pk>\d+)/delete/$', views.billing_delete, name='billing_delete'),
    url(r'^billings$', BillingListView.as_view(), name='billings'),
]

finance/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from core.models import TimeStampedModel
from reception.models import Patient
from operations.models import Treatment

# Create your models here.
class Billing(TimeStampedModel):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    treatment = models.ForeignKey(Treatment, on_delete=models.CASCADE)
    charges = models.CharField(max_length=200, default=0)

    def __str__(self):
        return '{}-{}'.format(self.patient, self.charges)

finance/forms.py
from django import forms
from finance.models import Billing

# crispy_forms imports
from crispy_forms.helper import FormHelper
from crispy_forms.layout import  Submit, Layout
from crispy_forms.bootstrap import PrependedAppendedText

class BillingForm(forms.ModelForm):
    # TODO: Define other fields here

    class Meta:
        model = Billing
        fields = ['patient', 'treatment', 'charges']

    def __init__(self, *args, **kwargs):
        super(BillingForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        # self.helper.form_class = 'form-horizontal'
        # self.helper.form_method = 'post'
        # self.helper.add_input(Submit('submit', 'Save'))
        self.helper.form_tag = False

        self.helper.layout = Layout(
            'patient',
            'treatment',
            PrependedAppendedText('charges', 'Kshs.', '.00'),
        )

    def clean(self):
        cleaned_data = super(BillingForm, self).clean()
        return cleaned_data

finance/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import reverse
from django.views.generic import CreateView, ListView
from finance.models import Billing
from finance.forms import BillingForm
from django.contrib.messages.views import SuccessMessageMixin

from django.http import JsonResponse
from django.template.loader import render_to_string
from django.shortcuts import render, get_object_or_404

# create fbv for a billing modal form for create, update and delete
def save_billing_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            billings = Billing.objects.all()
            data['html_billing_list'] = render_to_string("finance/includes/partial_billing_list.html",
                {'billings': billings}
            )
        else:
            data['form_is_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

def billing_create(request):
    if request.method == 'POST':
        form = BillingForm(request.POST)
    else:
        form = BillingForm()
    return save_billing_form(request, form, 'finance/billing_form.html')


def billing_update(request, pk):
    billing = get_object_or_404(Billing, pk=pk)
    if request.method == 'POST':
        form = BillingForm(request.POST, instance=billing)
    else:
        form = BillingForm(instance=billing)
    return save_billing_form(request, form, 'finance/billing_update.html')


def billing_delete(request, pk):
    billing = get_object_or_404(Billing, pk=pk)
    data = dict()
    if request.method == 'POST':
        billing.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        billings = Billing.objects.all()
        data['html_billing_list'] = render_to_string('finance/includes/partial_billing_list.html',
            {'billings': billings}
        )
    else:
        context = {'billing': billing}
        data['html_form'] = render_to_string('finance/billing_delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)


# Create listviews for the finance app
class BillingListView(ListView):
    context_object_name = 'billings'
    model = Billing
    template_name = 'finance/billing_list.html'

    def get_queryset(self):
        return Billing.objects.all()

finance/templates/finance/billing_delete.html
<form method="post" action="{% url 'finance:billing_delete' billing.id %}" class="js-billing-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm billing deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the billing of <strong>{{ billing.patient }}</strong>? </p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete Billing</button>
  </div>
</form>

finance/templates/finance/billing_form.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'finance:billing_create' %}" class="js-billing-create-form form-horizontal">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a Billing</h4>
  </div>

  <div class="modal-body">
      {% crispy form %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create Billing</button>
  </div>

</form>

finance/templates/finance/billing_list.html
{% extends 'hospital/base.html' %}

{% load staticfiles %}

{% block title %}billings{{ block.super }}{% endblock title %}

{% block javascript %}
  <script src="{% static 'finance/js/modal.js' %}"></script>
  <script src="{% static 'finance/css/style.css' %}"></script>
{% endblock javascript %}


{% block content %}
  <div class="container">
    <h1 class="page-header">Billings</h1>

    <!-- BUTTON TO TRIGGER THE ACTION -->
    <p>
      <button type="button"
              class="btn btn-primary js-create-billing"
              data-url="{% url 'finance:billing_create' %}">
        <span class="glyphicon glyphicon-plus"></span>
        New billing
      </button>
    </p>

    <table class="table" id="billing-table">
      <thead>
        <tr>
          <th>#</th>
          <th>Patient</th>
          <th>Treatment</th>
          <th>Charges</th>
        </tr>
      </thead>
      <tbody>
        {% include 'finance/includes/partial_billing_list.html' %}
      </tbody>
    </table>

    <!-- THE MODAL WE WILL BE USING -->
    <div class="modal fade" id="modal-billing">
      <div class="modal-dialog">
        <div class="modal-content">
        </div>
      </div>
    </div>

  </div>

{% endblock %}

finance/templates/finance/billing_update.html
{% load crispy_forms_tags %}

<form method="post" action="{% url 'finance:billing_update' pk=form.instance.pk %}" class="js-billing-update-form form-horizontal">
  {% csrf_token %}
  <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update Billing</h4>
  </div>

  <div class="modal-body">
      {% crispy form %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update Billing</button>
  </div>

</form>